2nd Edition + package.json cleanup
blakevanlan/KingdomCreator pull request #139
Opened 2023-01-07 14:49 UTC by gillesgros

Seaside2, Hinterlands2, Proisperity2, Package.json updated to last version except vue.js

2023-01-07 15:03 UTC, gillesgros commented
Hello,

I initialted a global pull request [#139 2nd Edition + package.json cleanup](https://github.com/blakevanlan/KingdomCreator/pull/139)](https://github.com/blakevanlan/KingdomCreator/pull/139)

I am not feeling confident in my knowledge of Git.
I will feel much more at ease if you review and do the merge.
  I need to practice on my side.

Regards,
Gilles

2023-01-08 02:49 UTC, markbrockettrobson requested changes
We need to add some changes from 115 :

 src/randomizer/randomizer.ts:
         some changes to make Colonies show up from PROSPERITY and PROSPERITY_2
kingdoms/nocturne.yaml:
         tag the kingdom "Day at the Races" with       
         - nocturne_boon_theswampsgift
         - nocturne_boon_theriversgift
         - nocturne_boon_theforestsgift

2023-01-08 02:49 UTC, markbrockettrobson commented on webpack.dev.js
> +/* webpack 3
do we want to get rid of all the old code ?

2023-01-08 02:49 UTC, markbrockettrobson commented on plugins/dominion-content-plugin.js
> +	  /* js-yamj v3 to v4
do we want to remove the old v3 code ?

2023-01-08 02:49 UTC, markbrockettrobson commented on process/loader.js
> +      /* js-yaml  v3 to v4
old code

2023-01-08 16:41 UTC, gillesgros commented
Changes made.
 Thanks for the review

2023-01-08 22:39 UTC, markbrockettrobson commented
We just need the changes to 
randomizer to make Colonies show up from PROSPERITY and PROSPERITY_2

You will find the in the 115pr

2023-01-10 22:18 UTC, gillesgros commented
Fix + update of kngdoms for proper colonies use. same for shelter

2023-01-11 02:05 UTC, markbrockettrobson approved these changes

2023-01-12 06:11 UTC, merged